"""
Aggregate Root for DDD.
"""
from __future__ import annotations

from typing import List

from pydantic import PrivateAttr

from searchops.shared.domain.entity import BaseEntity
from searchops.shared.domain.event import DomainEvent


class AggregateRoot(BaseEntity):
    """
    Base class for aggregate roots.
    
    Collects domain events generated by operations on the aggregate.
    """

    _domain_events: List[DomainEvent] = PrivateAttr(default_factory=list)

    def record_event(self, event: DomainEvent) -> None:
        """
        Record a domain event to be dispatched later.
        
        Args:
            event: The domain event that occurred.
        """
        self._domain_events.append(event)

    def collect_events(self) -> List[DomainEvent]:
        """
        Retrieve all pending events and clear the collection.
        
        Returns:
            A list of pending domain events.
        """
        events = list(self._domain_events)
        self._domain_events.clear()
        return events

    def has_pending_events(self) -> bool:
        """
        Check if there are any uncommitted domain events.
        
        Returns:
            True if there are pending events, False otherwise.
        """
        return len(self._domain_events) > 0
