import React, { useState, useCallback, useRef, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeHighlight from 'rehype-highlight';
import 'highlight.js/styles/github-dark.css';
import { useExecutionStore } from '../shared/store/useExecutionStore';
import { FileText, Download, Copy, Check, Search, BookOpen, X } from 'lucide-react';

interface TocEntry {
  text: string;
  level: 1 | 2 | 3;
  slug: string;
}

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function buildToc(markdown: string): TocEntry[] {
  const entries: TocEntry[] = [];
  const seen: Record<string, number> = {};
  for (const line of markdown.split('\n')) {
    const h3 = line.match(/^### (.+)/);
    const h2 = line.match(/^## (.+)/);
    const h1 = line.match(/^# (.+)/);
    const match = h1 ?? h2 ?? h3;
    const level = h1 ? 1 : h2 ? 2 : h3 ? 3 : null;
    if (!match || !level) continue;
    const text = match[1].trim();
    let slug = slugify(text);
    seen[slug] = (seen[slug] ?? 0) + 1;
    if (seen[slug] > 1) slug = `${slug}-${seen[slug] - 1}`;
    entries.push({ text, level: level as 1 | 2 | 3, slug });
  }
  return entries;
}

export const ReportsViewer: React.FC = () => {
  const { report } = useExecutionStore();
  const [copied, setCopied] = useState(false);
  const [searchText, setSearchText] = useState('');
  const [searchVisible, setSearchVisible] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);
  const searchRef = useRef<HTMLInputElement>(null);

  // Focus search input when visible
  useEffect(() => {
    if (searchVisible) searchRef.current?.focus();
  }, [searchVisible]);

  const handleCopy = useCallback(() => {
    if (!report) return;
    navigator.clipboard.writeText(report.markdownContent).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [report]);

  const handleDownload = useCallback(() => {
    if (!report) return;
    const blob = new Blob([report.markdownContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}_report.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [report]);

  const scrollToHeading = useCallback((slug: string) => {
    const el = contentRef.current?.querySelector(`#${CSS.escape(slug)}`);
    el?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }, []);

  if (!report) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center p-12 bg-slate-950">
        <div className="flex flex-col items-center p-10 border border-dashed border-slate-800 rounded-lg text-slate-600 bg-slate-950/60 max-w-sm gap-3">
          <FileText className="w-8 h-8 text-slate-700" />
          <p className="font-sans text-xs text-slate-500">No synthesized report available.</p>
          <p className="font-sans text-[10px] text-slate-600 text-center leading-relaxed">
            Reports are generated by the report writer node upon successful graph execution.
          </p>
        </div>
      </div>
    );
  }

  const toc = buildToc(report.markdownContent);

  // Filter content by search (highlight matching paragraphs)
  const filteredContent = searchText.trim()
    ? report.markdownContent
        .split('\n')
        .filter(line => line.toLowerCase().includes(searchText.toLowerCase()))
        .join('\n') || report.markdownContent // fallback to full if no matches
    : report.markdownContent;

  // Custom heading components with id anchors for ToC navigation
  const components = {
    h1: ({ children, ...props }: React.HTMLAttributes<HTMLHeadingElement>) => {
      const text = String(children ?? '');
      const slug = slugify(text);
      return <h1 id={slug} className="text-lg font-bold border-b border-slate-800 pb-2 pt-4 text-emerald-400 font-sans tracking-tight scroll-mt-4" {...props}>{children}</h1>;
    },
    h2: ({ children, ...props }: React.HTMLAttributes<HTMLHeadingElement>) => {
      const text = String(children ?? '');
      const slug = slugify(text);
      return <h2 id={slug} className="text-base font-bold pt-3 pb-1 text-cyan-400 font-sans tracking-tight scroll-mt-4" {...props}>{children}</h2>;
    },
    h3: ({ children, ...props }: React.HTMLAttributes<HTMLHeadingElement>) => {
      const text = String(children ?? '');
      const slug = slugify(text);
      return <h3 id={slug} className="text-sm font-bold pt-2 text-indigo-400 font-sans tracking-tight scroll-mt-4" {...props}>{children}</h3>;
    },
    p: ({ children }: { children?: React.ReactNode }) => <p className="text-slate-300 leading-relaxed font-sans text-sm">{children}</p>,
    a: ({ children, ...props }: React.AnchorHTMLAttributes<HTMLAnchorElement>) => <a className="text-emerald-400 underline underline-offset-2 hover:text-emerald-300 transition-colors" target="_blank" rel="noopener noreferrer" {...props}>{children}</a>,
    ul: ({ children }: { children?: React.ReactNode }) => <ul className="list-disc pl-5 space-y-1 text-slate-300 text-sm">{children}</ul>,
    ol: ({ children }: { children?: React.ReactNode }) => <ol className="list-decimal pl-5 space-y-1 text-slate-300 text-sm">{children}</ol>,
    li: ({ children }: { children?: React.ReactNode }) => <li className="leading-relaxed">{children}</li>,
    blockquote: ({ children }: { children?: React.ReactNode }) => <blockquote className="border-l-2 border-emerald-500/40 pl-4 italic text-slate-400 my-2">{children}</blockquote>,
    table: ({ children }: { children?: React.ReactNode }) => <div className="overflow-x-auto my-4"><table className="w-full text-xs border-collapse border border-slate-800">{children}</table></div>,
    thead: ({ children }: { children?: React.ReactNode }) => <thead className="bg-slate-900">{children}</thead>,
    th: ({ children }: { children?: React.ReactNode }) => <th className="border border-slate-800 px-3 py-2 text-left text-slate-300 font-semibold">{children}</th>,
    td: ({ children }: { children?: React.ReactNode }) => <td className="border border-slate-800 px-3 py-2 text-slate-400">{children}</td>,
    code: ({ children, className }: React.HTMLAttributes<HTMLElement>) => {
      const isBlock = className?.startsWith('language-');
      return isBlock
        ? <code className={`${className ?? ''} text-xs`}>{children}</code>
        : <code className="bg-slate-900 text-emerald-300 px-1.5 py-0.5 rounded text-xs font-mono">{children}</code>;
    },
    pre: ({ children }: { children?: React.ReactNode }) => (
      <pre className="bg-slate-900 border border-slate-800 rounded-lg overflow-x-auto text-xs my-4 p-4">
        {children}
      </pre>
    ),
  };

  return (
    <div className="flex-1 flex h-full bg-slate-950 overflow-hidden select-text">
      {/* Main Report Canvas */}
      <div className="flex-1 flex flex-col overflow-hidden border-r border-slate-900">
        {/* Controls Header */}
        <div className="bg-slate-900 border-b border-slate-800 p-2.5 flex items-center justify-between shrink-0 select-none">
          <div className="flex items-center space-x-2">
            <FileText className="w-4 h-4 text-emerald-400" />
            <span className="font-bold text-slate-100 uppercase text-[11px] font-sans tracking-wide">Synthesized Intelligence Report</span>
          </div>
          <div className="flex items-center space-x-2">
            {/* Search toggle */}
            <button
              onClick={() => setSearchVisible(v => !v)}
              title="Find in report"
              className="bg-slate-950 hover:bg-slate-850 border border-slate-800 text-slate-300 px-2.5 py-1 rounded font-bold transition flex items-center space-x-1 text-[10px]"
            >
              {searchVisible ? <X className="w-3.5 h-3.5" /> : <Search className="w-3.5 h-3.5" />}
              <span className="hidden sm:inline">{searchVisible ? 'CLOSE' : 'FIND'}</span>
            </button>
            <button onClick={handleCopy} className="bg-slate-950 hover:bg-slate-850 border border-slate-800 text-slate-300 px-2.5 py-1 rounded font-bold transition flex items-center space-x-1 text-[10px]">
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'COPIED' : 'COPY'}</span>
            </button>
            <button onClick={handleDownload} className="bg-slate-950 hover:bg-slate-850 border border-slate-800 text-slate-300 px-2.5 py-1 rounded font-bold transition flex items-center space-x-1 text-[10px]">
              <Download className="w-3.5 h-3.5" />
              <span>DOWNLOAD</span>
            </button>
          </div>
        </div>

        {/* Search bar (collapsible) */}
        {searchVisible && (
          <div className="bg-slate-950 border-b border-slate-800 px-4 py-2 flex items-center space-x-2">
            <Search className="w-3.5 h-3.5 text-slate-500 shrink-0" />
            <input
              ref={searchRef}
              type="text"
              value={searchText}
              onChange={e => setSearchText(e.target.value)}
              placeholder="Search report content..."
              className="flex-1 bg-transparent border-none text-xs text-slate-200 focus:outline-none placeholder-slate-600 font-mono"
            />
            {searchText && (
              <button onClick={() => setSearchText('')} className="text-slate-500 hover:text-slate-300">
                <X className="w-3 h-3" />
              </button>
            )}
            {searchText && (
              <span className="text-slate-500 text-[10px] font-mono">
                {filteredContent === report.markdownContent ? '0 matches' : 'filtered'}
              </span>
            )}
          </div>
        )}

        {/* Report Content */}
        <div ref={contentRef} className="flex-1 overflow-y-auto p-6 max-w-4xl mx-auto w-full">
          <div className="border-b border-slate-800 pb-4 mb-6 select-none">
            <h1 className="text-xl font-bold text-slate-100 tracking-tight font-sans">{report.title}</h1>
            <div className="flex items-center space-x-3 text-[10px] text-slate-500 font-mono mt-1">
              <span>Deep Synthesis Ensemble v4.2</span>
              <span>•</span>
              <span>{report.generatedAt}</span>
              <span>•</span>
              <span>{report.sourcesCount} sources</span>
              <span>•</span>
              <span>{report.entitiesCount} entities</span>
            </div>
          </div>

          <ReactMarkdown
            remarkPlugins={[remarkGfm]}
            rehypePlugins={[rehypeHighlight]}
            components={components as never}
          >
            {filteredContent}
          </ReactMarkdown>
        </div>
      </div>

      {/* ToC Sidebar */}
      <div className="w-52 bg-slate-900/40 p-3 overflow-y-auto hidden lg:block shrink-0 select-none">
        <div className="flex items-center space-x-1.5 text-slate-400 font-bold uppercase text-[9px] mb-3 pb-1.5 border-b border-slate-800">
          <BookOpen className="w-3.5 h-3.5 text-emerald-400" />
          <span>Contents</span>
        </div>
        <nav className="space-y-1">
          {toc.length === 0 && (
            <p className="text-slate-600 text-[9px]">No headings found</p>
          )}
          {toc.map((item, i) => (
            <button
              key={i}
              onClick={() => scrollToHeading(item.slug)}
              className={`w-full text-left hover:text-slate-200 cursor-pointer transition text-slate-450 truncate block ${
                item.level === 1 ? 'font-bold text-[10px] pl-0' :
                item.level === 2 ? 'pl-3 text-[10px]' : 'pl-5 text-[9px]'
              }`}
              title={item.text}
            >
              {item.text}
            </button>
          ))}
        </nav>
      </div>
    </div>
  );
};
export default ReportsViewer;
